(in-package :academy)

;; http://en.wikipedia.org/wiki/NATO_phonetic_alphabet

(defparameter *nato-phonetic-alphabet*
  '((#\a alfa)
    (#\b bravo)
    (#\c charlie)
    (#\d delta)
    (#\e echo)
    (#\f foxtrot)
    (#\g golf)
    (#\h hotel)
    (#\i india)
    (#\j juliet)
    (#\k kilo)
    (#\l lima)
    (#\m mike)
    (#\n november)
    (#\o oscar)
    (#\p papa)
    (#\q quebec)
    (#\r romeo)
    (#\s sierra)
    (#\t tango)
    (#\u uniform)
    (#\v victor)
    (#\w whiskey)
    (#\x xray)
    (#\y yankee)
    (#\z zulu)
    (#\1 one)
    (#\2 two)
    (#\3 three)
    (#\4 four)
    (#\5 five)
    (#\6 six)
    (#\7 seven)
    (#\8 eight)
    (#\9 nine)
    (#\0 zero)))

(defun string-to-phonetic-alphabet (string)
  (loop for char across (string-downcase string)
        collect (or (second (assoc char *nato-phonetic-alphabet* :test #'char=))
                    (error "Unknown NATO chararacter ~S." char))))
